<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #00bf16;
    }

    div#welcome
    {
        color: #000000;
        height: 400px;
       /* border: 2px solid #444444; */
        overflow: hidden;
        text-align: center;
	margin-left: auto;
	margin-right: auto;
	font-family: Verdana, sans-serif;
	font-size:85%;
    }

    div#welcome p {
	text-align: justify;
    }

    div#more-information
    {
        height: 100%;
    }

    div#more-information p {
	text-align: center;
    }
</style>
<div id="welcome">
    <h1>Welcome to <span id="zf-name">New Life Copenhagen</span></h1>

    <p>NEW LIFE COPENHAGEN is an ongoing hospitality experiment taking place in Copenhagen, Denmark.
    The project connects foreign visitors coming to Copenhagen with local Danes who like to host interesting guests. Using these meetings as our platform, we invite our participants to live together - and to live in 
    new ways.</p>

    <p>The first time NEW LIFE COPENHAGEN took place was during the United Nations (UN) Climate Change 
    Conference from December 7th to 18th, 2009. For this occasion we hosted more than 3.000 climate activists for free with Danish families, had over 100 international articles written about the project, as well as TV reports to 102 million viewers across the planet.</p>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>
