<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('New Life Copenhagen');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>
</head>
<body>
	<div id="siteheader">
		NEW LIFE COPENHAGEN
	</div>
	<div id="sitenav">
		<?php echo $this->siteNavigation(); ?> | 
		<?php echo $this->loggedInUser(); ?>
	</div>
	<div id="content">
		<?php echo $this->layout()->content; ?>
	</div>
	<div id="footer">
		<a href="http://framework.zend.com/"><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></a>
	</div>
</body>
</html>
