<h1>About</h1>


<p>NEW LIFE COPENHAGEN is an ongoing hospitality experiment taking place in Copenhagen, Denmark.
The project connects foreign visitors coming to Copenhagen with local Danes who like to host interesting guests. Using these meetings as our platform, we invite our participants to live together - and to live in 
new ways.</p>

<p>The first time NEW LIFE COPENHAGEN took place was during the United Nations (UN) Climate Change 
Conference from December 7th to 18th, 2009. For this occasion we hosted more than 3.000 climate activists for free with Danish families, had over 100 international articles written about the project, as well as TV reports to 102 million viewers across the planet.</p>

<p>This year, we are happy to find accommodation for many great participants in the bicycle conference Velo-city Global 2010, the art festival My World IMAGES and the music festivals Distortion, Strøm, Start! Festival and Displaced Expressions among others.</p>

<p>To learn more or to take part yourself - please visit us on Facebook or write an email to <a href="mailto:contact@newlifecopenhagen.com">contact@newlifecopenhagen.com</a></p>

<p>You're welcome!</p>
 
<h2>PARTICIPATE OR DIE</h2>

<p>From December 7th to 18th, 2009, representatives from 192 nations gathered in Denmark for the UN Climate Change Conference. Their offical goal was to reach agreement on a new global climate treaty to replace the Kyoto Protocol.</p>

<p>In addition to the large number of official UN delegates, thousands of activists and Non-Governmental Organizations were bound for the conference which was called: “Humanity's last chance to combat a climate problem that is now all but overwhelming.” (Tim Flannery, Scientist and environmental activist)</p>

<p>However, there was not enough hotel space to accommodate most of these visitors, as all hotels in Copenhagen and the surrounding area (including Sweden) had already been booked for the official delegates. Furthermore, even if they were available, many visitors from all over the world could not afford them anyway.</p>

<p>In order to help solve this substantial problem, Wooloo ran a year-long volunteer-based campaign in Copenhagen asking private families to open up their homes for the activists. By November 2009, this initiative had created free housing for more than 3,000 activists and climate campaigners coming to Copenhagen from over 100 countries!</p>

<p>Utilizing this large-scale human meeting as our exhibition platform, we then invited artists to explore its social architecture.</p>

<p>Using an Open Call on Wooloo.org, we asked artists for ways to challenge this human meeting. Both the grand meeting of thousands and the intimate meeting of guest and host.</p>

<p>Can the climate crisis be more than just a threat for humanity? Could it be our greatest opportunity: the opportunity to create transnational commitment around a radical re-thinking of a destructive economic system that thrives on exploiting natural resources and people?</p>

<p>We soon began to receive the first suggestions for rules, rituals and guidelines for interaction. The rest came organically when the many guests started contacting us with their reasons and agendas for coming to Copenhagen.</p>

<p>Out of all the many ideas we received from locals and visitors alike, we went on to select the following to share with you. By doing so, our aim was not to represent a set of fixed cultural conclusions, but to create a model for a fluid cultural landscape. A way for you to experience, to envision and to live a new life.</p>


<h2>SUPERFLEX (DK)</h2>

<p>Superflex used the context of the climate conference to respond to the increasing amount of goods marketed towards our ´green´ conscience. Through a legal contract they asked if each participant – in case of death during the climate conference – would commit themselves to being buried in an newly developed ecological way?</p>

<h2>THE YES MEN (US)</h2>
<p>Copenhagen Pledge was an activist intervention and campaign against Coca-Cola made by The Yes Men in collaboration with the India Resource Center. Coca-Cola is being criticized for stealing water from local communities around the world, and as a reaction to this The Yes Men urge us to take a pledge to never drink Coca-Cola again.</p>

<h2>RAKETA (S)</h2>
<p>Raketa has infiltrated the NEW LIFE COPENHAGEN matching system and selected ten hosts and guests for their exclusive Home Away Resort. Throughout the conference period, Raketa provided the participants with instructions and special services to challenge the roles of home and away.</p>

<h2>OPEN DIALOGUES (UK)</h2>
<p>Open Dialogues performed a series of 1.000 interviews conducted throughout the climate conference. With their exploratory approach, Open Dialogues sought to build up an archive and stream of statements, situations and reflections on participation in the Climate Change Conference and NEW LIFE COPENHAGEN.</p>

<h2>CLIMATE JUSTICE FAST! (Global)</h2>
<p>Climate Justice Fast! was an international hunger strike taking place from the 6th of November to the end of the Climate Conference on the 18th of December. Four fasting activists and a medical assistant were staying with a Danish hosting family. On December 7th - the first day of the Climate Conference and one month after the fast began - the hosting family stopped eating for 24 hours in sympathy for the activists and we invited all 6,000+ NEW LIFE COPENHAGEN participants to do the same.</p>

<h2>SIGNA (A/DK)</h2>
<p>The performance duo Signa created a book that was sent to all participating hosts and guests in Copenhagen. The intention of the publication was to examine and evaluate the extensive encounter of hospitable families and climate activists from all over the world. Through a specially developed questionnaire, the book sought to influence the outcome and experience of their meeting.</p>
